# Generated by Django 5.2.17 on 2026-10-04 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Main Unit', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_units', to='narrative.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShootDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('calendar_date', models.DateField()),
                ('general_crew_call', models.TimeField(blank=True, null=True)),
                ('shooting_call', models.TimeField(blank=True, null=True)),
                ('hospital_address', models.TextField(blank=True, default='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_days', to='logistics.productionunit')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='StripboardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('item_type', models.CharField(choices=[('SCENE', 'SCENE'), ('BANNER', 'BANNER')], default='SCENE', max_length=20)),
                ('banner_label', models.CharField(blank=True, default='', max_length=255)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripboard_items', to='narrative.scene')),
                ('shoot_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripboard_items', to='logistics.shootday')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
