# Generated by Django 5.2.17 on 2026-10-06 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_historicalshootday_historicalstripboarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_first_shot', models.TimeField(blank=True, null=True)),
                ('actual_wrap', models.TimeField(blank=True, null=True)),
                ('scenes_completed', models.PositiveIntegerField(default=0)),
                ('pages_completed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('camera_rolls_used', models.PositiveIntegerField(default=0)),
                ('sound_rolls_used', models.PositiveIntegerField(default=0)),
                ('delay_notes', models.TextField(blank=True)),
                ('shoot_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpr', to='logistics.shootday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
