# Generated by Django 5.2.18 on 2026-10-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_crewmember'),
        ('narrative', '0006_adrcue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmember',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='crewmember',
            name='day_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='union_affiliation',
            field=models.CharField(default='Non-Union', max_length=100),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='narrative.project'),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
