# Generated by Django 5.2.18 on 2026-10-08 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrative', '0006_adrcue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_code', models.CharField(default='A', max_length=20)),
                ('camera_movement', models.CharField(choices=[('STATIC', 'Static / Locked-off'), ('PAN', 'Pan / Tilt'), ('TRACK', 'Tracking / Dolly'), ('STEADI', 'Steadicam / Gimbal'), ('CRANE', 'Crane / Jib'), ('DRONE', 'Drone / Aerial')], default='STATIC', max_length=10)),
                ('equipment_notes', models.TextField(blank=True, default='')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_setups', to='narrative.scene')),
            ],
            options={
                'ordering': ['setup_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shot_code', models.CharField(default='A1', max_length=20)),
                ('shot_size', models.CharField(choices=[('WS', 'Wide Shot'), ('MS', 'Medium Shot'), ('CU', 'Close Up'), ('ECU', 'Extreme Close Up'), ('INS', 'Insert'), ('POV', 'Point of View')], default='MS', max_length=5)),
                ('lens', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('vfx_required', models.BooleanField(default=False)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='shots.camerasetup')),
            ],
            options={
                'ordering': ['shot_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('take_number', models.PositiveIntegerField(default=1)),
                ('is_circle_take', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('director_notes', models.TextField(blank=True, default='')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='shots.shot')),
            ],
            options={
                'ordering': ['take_number'],
            },
        ),
        migrations.CreateModel(
            name='VfxShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vfx_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('frame_count', models.PositiveIntegerField(default=0)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfx_shots', to='narrative.scene')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
