# Generated by Django 5.2.17 on 2026-10-04 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_code', models.CharField(default='A', max_length=20)),
                ('lighting_package_notes', models.TextField(blank=True, default='')),
                ('overhead_floorplan_url', models.URLField(blank=True, default='', max_length=500)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_setups', to='narrative.scene')),
            ],
            options={
                'ordering': ['setup_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shot_code', models.CharField(default='1', max_length=20)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('shot_size', models.CharField(default='MCU', max_length=50)),
                ('focal_length', models.CharField(default='35mm', max_length=50)),
                ('camera_movement', models.CharField(default='Static', max_length=50)),
                ('framing_description', models.TextField(blank=True, default='')),
                ('storyboard_frame_url', models.URLField(blank=True, default='', max_length=500)),
                ('covered_script_blocks', models.JSONField(blank=True, default=list)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='shots.camerasetup')),
            ],
            options={
                'ordering': ['order_index', 'shot_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('take_number', models.PositiveIntegerField(default=1)),
                ('is_circle_take', models.BooleanField(default=False)),
                ('camera_card', models.CharField(blank=True, default='A001', max_length=50)),
                ('sound_roll', models.CharField(blank=True, default='SR01', max_length=50)),
                ('timecode_in', models.CharField(blank=True, default='01:00:00:00', max_length=20)),
                ('timecode_out', models.CharField(blank=True, default='01:01:15:12', max_length=20)),
                ('script_supervisor_notes', models.TextField(blank=True, default='')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='shots.shot')),
            ],
            options={
                'ordering': ['take_number'],
            },
        ),
    ]
