# Generated by Django 5.2.17 on 2026-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='storyboard_frame_url',
            field=models.ImageField(blank=True, null=True, upload_to='storyboards/'),
        ),
    ]
