# Generated by Django 5.2.18 on 2026-10-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vfxshot',
            name='status',
            field=models.CharField(choices=[('PRE_VIS', 'Pre-Vis'), ('ROTO', 'Roto & Prep'), ('COMPOSITING', 'Compositing'), ('FINAL', 'Final')], default='PRE_VIS', max_length=50),
        ),
    ]
