# Generated by Django 5.2.17 on 2026-10-06 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0005_project_poster_historicalscene'),
        ('shots', '0002_alter_shot_storyboard_frame_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VfxShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vfx_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('frame_count', models.PositiveIntegerField(default=0)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vfx_shots', to='narrative.scene')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
