# Generated by Django 5.2.18 on 2026-10-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0006_adrcue'),
        ('shots', '0003_vfxshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shot',
            options={},
        ),
        migrations.RemoveField(
            model_name='shot',
            name='covered_script_blocks',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='framing_description',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='shot_code',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='storyboard_frame_url',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shot',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='estimated_setup_time',
            field=models.IntegerField(default=15, help_text='Setup time in minutes'),
        ),
        migrations.AddField(
            model_name='shot',
            name='lens',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='scene',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='narrative.scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='vfx_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shot',
            name='camera_movement',
            field=models.CharField(choices=[('STATIC', 'Static / Locked-off'), ('PAN', 'Pan / Tilt'), ('TRACK', 'Tracking / Dolly'), ('STEADI', 'Steadicam / Gimbal'), ('HH', 'Handheld'), ('CRANE', 'Crane / Jib'), ('DRONE', 'Drone / Aerial')], default='STATIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shot_size',
            field=models.CharField(choices=[('WS', 'Wide Shot'), ('MS', 'Medium Shot'), ('CU', 'Close Up'), ('ECU', 'Extreme Close Up'), ('INS', 'Insert'), ('POV', 'Point of View')], default='MS', max_length=5),
        ),
    ]
