# Generated by Django 5.2.17 on 2026-10-06 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrative', '0005_project_poster_historicalscene'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('ATL', 'ATL'), ('BTL_PRODUCTION', 'BTL_PRODUCTION'), ('BTL_POST', 'BTL_POST'), ('OTHER', 'OTHER')], max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_accounts', to='narrative.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_actual', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='financials.budgetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
