# Generated by Django 5.2.17 on 2026-10-04 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cast_id_number', models.PositiveIntegerField(default=1)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='narrative.project')),
            ],
            options={
                'ordering': ['cast_id_number'],
            },
        ),
        migrations.CreateModel(
            name='CostumeLook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('look_number', models.CharField(default='Look 1', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('continuity_photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costume_looks', to='breakdown.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('gps_coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('sun_path_notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_locations', to='narrative.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_hero_prop', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='narrative.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SceneBreakdownItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_type', models.CharField(choices=[('PROP', 'PROP'), ('WARDROBE', 'WARDROBE'), ('SOUND', 'SOUND'), ('SFX', 'SFX'), ('VFX', 'VFX')], default='PROP', max_length=50)),
                ('custom_notes', models.TextField(blank=True, default='')),
                ('is_continuity_critical', models.BooleanField(default=False)),
                ('costume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_items', to='breakdown.costumelook')),
                ('prop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_items', to='breakdown.prop')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_items', to='narrative.scene')),
            ],
            options={
                'ordering': ['element_type', 'created_at'],
            },
        ),
    ]
