# Generated by Django 5.2.17 on 2026-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumelook',
            name='continuity_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='costumes/'),
        ),
    ]
