# Generated by Django 5.2.18 on 2026-10-08 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0002_alter_costumelook_continuity_photo_url'),
        ('narrative', '0007_alter_adrcue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenebreakdownitem',
            name='element_type',
            field=models.CharField(choices=[('CAST', 'Cast'), ('PROPS', 'Props'), ('WARDROBE', 'Wardrobe'), ('VFX', 'VFX'), ('SFX', 'SFX'), ('STUNTS', 'Stunts'), ('VEHICLES', 'Vehicles'), ('SOUND', 'Sound'), ('SET_DRESSING', 'Set Dressing')], default='PROPS', max_length=50),
        ),
        migrations.CreateModel(
            name='ContinuityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CAST', 'Cast'), ('PROPS', 'Props'), ('WARDROBE', 'Wardrobe'), ('VFX', 'VFX'), ('SFX', 'SFX'), ('STUNTS', 'Stunts'), ('VEHICLES', 'Vehicles'), ('SOUND', 'Sound'), ('SET_DRESSING', 'Set Dressing')], default='PROPS', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_photos', to='narrative.scene')),
            ],
        ),
    ]
