# Generated by Django 5.2.18 on 2026-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_alter_scenebreakdownitem_element_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContinuityPhoto',
        ),
    ]
