from typing import Protocol, List, Optional
import uuid
from apps.core.studio.application.dtos import (
    ProjectDTO,
    CreateProjectCommand,
    CrewMemberDTO,
    AddCrewMemberCommand,
)
from apps.shots.application.dtos import VfxShotDTO

class IStudioRepository(Protocol):
    def list_projects(self) -> List[ProjectDTO]: ...
    def slug_exists(self, slug: str) -> bool: ...
    def create_project(self, command: CreateProjectCommand, resolved_slug: str, creator_user=None) -> ProjectDTO: ...
    def list_vfx_shots(self, project_id: uuid.UUID) -> List[VfxShotDTO]: ...
    def update_vfx_status(self, project_id: uuid.UUID, shot_id: uuid.UUID, status: str) -> VfxShotDTO: ...
    def list_crew(self, project_id: uuid.UUID) -> List[CrewMemberDTO]: ...
    def add_crew(self, project_id: uuid.UUID, command: AddCrewMemberCommand) -> CrewMemberDTO: ...
