from typing import Protocol, List
import uuid
from apps.shots.application.dtos import (
    CameraSetupDTO,
    ShotDTO,
    TakeDTO,
    SceneCoverageDTO,
    CreateSetupCommand,
    CreateShotCommand,
    CreateTakeCommand,
    VfxShotDTO,
    CreateVfxShotCommand,
    UpdateVfxShotCommand,
)

class IShotsRepository(Protocol):
    def get_scene_coverage(self, scene_id: uuid.UUID) -> SceneCoverageDTO: ...
    def create_setup(self, command: CreateSetupCommand) -> CameraSetupDTO: ...
    def create_shot(self, command: CreateShotCommand) -> ShotDTO: ...
    def create_take(self, command: CreateTakeCommand) -> TakeDTO: ...

class IVfxRepository(Protocol):
    def list_by_project(self, project_id: uuid.UUID) -> List[VfxShotDTO]: ...
    def create_shot(self, project_id: uuid.UUID, command: CreateVfxShotCommand) -> VfxShotDTO: ...
    def update_shot(self, shot_id: uuid.UUID, command: UpdateVfxShotCommand) -> VfxShotDTO: ...
    def update_status(self, shot_id: uuid.UUID, status: str) -> VfxShotDTO: ...
    def delete_shot(self, shot_id: uuid.UUID) -> None: ...
