# Generated by Django 5.2.17 on 2026-10-04 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('aspect_ratio', models.CharField(default='2.39:1', max_length=20)),
                ('target_runtime_minutes', models.PositiveIntegerField(default=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('target_page_length', models.FloatField(default=30.0)),
                ('dramatic_milestone', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='narrative.project')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('color_tag', models.CharField(default='#3B82F6', max_length=50)),
                ('dramatic_question', models.TextField(blank=True, default='')),
                ('temp_score_reference', models.CharField(blank=True, default='', max_length=255)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='narrative.act')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_number', models.CharField(max_length=20)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('int_ext', models.CharField(choices=[('INT', 'INT'), ('EXT', 'EXT'), ('INT/EXT', 'INT/EXT')], default='INT', max_length=10)),
                ('set_name', models.CharField(max_length=255)),
                ('time_of_day', models.CharField(default='DAY', max_length=50)),
                ('pages_eighths', models.PositiveSmallIntegerField(default=8)),
                ('estimated_shoot_minutes', models.PositiveIntegerField(default=120)),
                ('script_data', models.JSONField(blank=True, default=dict)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='narrative.sequence')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
