# Generated by Django 5.2.17 on 2026-10-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
        ('narrative', '0002_sequence_continuity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='master_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='breakdown.masterlocation'),
        ),
    ]
