# Generated by Django 5.2.17 on 2026-10-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0003_scene_master_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PRE_PRODUCTION', 'Pre-Production'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post-Production'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PRE_PRODUCTION', max_length=50),
        ),
    ]
