# Generated by Django 5.2.17 on 2026-10-06 09:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0002_alter_costumelook_continuity_photo_url'),
        ('narrative', '0004_project_deleted_at_project_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.CreateModel(
            name='HistoricalScene',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('scene_number', models.CharField(max_length=20)),
                ('order_index', models.CharField(default='0|hzzzzz:', max_length=50)),
                ('int_ext', models.CharField(choices=[('INT', 'INT'), ('EXT', 'EXT'), ('INT/EXT', 'INT/EXT')], default='INT', max_length=10)),
                ('set_name', models.CharField(max_length=255)),
                ('time_of_day', models.CharField(default='DAY', max_length=50)),
                ('pages_eighths', models.PositiveSmallIntegerField(default=8)),
                ('estimated_shoot_minutes', models.PositiveIntegerField(default=120)),
                ('script_data', models.JSONField(blank=True, default=dict)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='breakdown.masterlocation')),
                ('sequence', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='narrative.sequence')),
            ],
            options={
                'verbose_name': 'historical scene',
                'verbose_name_plural': 'historical scenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
