# Generated by Django 5.2.18 on 2026-10-08 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0005_project_poster_historicalscene'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRCue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=255)),
                ('line_text', models.TextField()),
                ('timecode', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_cues', to='narrative.scene')),
            ],
        ),
    ]
