# Generated by Django 5.2.18 on 2026-10-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0006_adrcue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrcue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECORDED', 'Recorded'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
    ]
